# Generated by Django 4.0.2 on 2022-03-02 05:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='theropy',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BT', 'BT'), ('OT', 'OT'), ('ST', 'ST'), ('PT', 'PT'), ('SE', 'SE')], max_length=2),
        ),
    ]
