# Generated by Django 4.0.2 on 2022-03-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_clienttable_theropy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='theropy',
            field=models.CharField(choices=[('BT', 'BT'), ('OT', 'OT'), ('ST', 'ST'), ('PT', 'PT'), ('SE', 'SE')], max_length=2),
        ),
    ]
