# Generated by Django 4.0.2 on 2022-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_clienttable_theropy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='theropy',
            field=models.CharField(max_length=2),
        ),
    ]
