# Generated by Django 4.0.2 on 2022-03-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_assesment_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='theropy',
            field=models.CharField(max_length=100),
        ),
    ]
