# Generated by Django 4.0.2 on 2022-03-04 04:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_clienttable_theropy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='assessment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BT', 'BT'), ('OT', 'OT'), ('ST', 'ST')], max_length=10),
        ),
    ]
