# Generated by Django 4.0.2 on 2022-03-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_clienttable_theropy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
