# Generated by Django 4.0.2 on 2022-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_user_created_by_user_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='discontinious',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
