# Generated by Django 4.0.2 on 2022-03-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_clienttable_discontinious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='discontinious',
            field=models.CharField(default='False', max_length=8),
        ),
    ]
