# Generated by Django 4.0.2 on 2022-03-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_clienttable_discontinious'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttable',
            name='created_on',
            field=models.DateField(),
        ),
    ]
